/**
 * Card-coverage ledger. The registry is the source of truth for what's IMPLEMENTED (hand-coded,
 * non-fallback). This regenerates docs/CARD-COVERAGE.md (a committed, human-readable list) on each
 * local run and asserts a floor so an accidental mass-removal fails CI. In CI it only asserts (no
 * write). To feed new cards into the perpetual coverage program, add them to the starter pool and
 * re-run the suite — the count + list here update automatically.
 */
import { describe, expect, it } from 'vitest'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { implementedCardNames, implementedCommanderNames } from '../../server/rules/cards/registry.ts'

describe('card coverage ledger', () => {
  it('regenerates docs/CARD-COVERAGE.md and holds the coverage floor', () => {
    const names = implementedCardNames()
    const commanders = implementedCommanderNames()
    expect(names.length).toBeGreaterThanOrEqual(240) // floor — guards accidental mass-removal
    expect(new Set(names).size).toBe(names.length) // no duplicate display names

    if (!process.env.CI) {
      const md = [
        '# Implemented card coverage',
        '',
        '> Auto-generated by `tests/unit/card-coverage.spec.ts` (the registry is the source of truth).',
        '> Regenerated on every local `pnpm test` run. This is the ledger for the perpetual',
        '> card-by-card coverage program (roadmap M-R5+).',
        '',
        `**${names.length} cards implemented** (hand-coded, non-fallback; excludes tokens & DFC back faces).`,
        `**${commanders.length}** of them can be a commander (legendary creatures).`,
        '',
        '## Cards',
        '',
        ...names.map((n) => `- ${n}`),
        '',
      ].join('\n')
      writeFileSync(fileURLToPath(new URL('../../docs/CARD-COVERAGE.md', import.meta.url)), md)
    }
  })
})
